### ISSUE TITLE
Question regarding pre-release.

### ISSUE THREAD

**Issue by jrosebr1** [realbig/PL_PYIS_ADDRESS_COLLECTION#7]
I see the [pre-release](https://github.com/realbig/PL_PYIS_ADDRESS_COLLECTION/releases/tag/v0.1.0) is ready to go, awesome!

Obviously we are using the development server to create this plugin. The "Address Collection" plugin is already installed there. My question is: *What should I be testing?* The plugin itself? Or how CognitoForms + Drip API are being used together?

Again, I just want to make sure I'm testing the correct parts of the plugin. I assume I should be adding subscribers to Drip, tagging them (or not), and then entering data into CognitoForms, and then finally seeing if the proper changes are made in Drip. Am I correct? Again, I just want to make sure I'm testing the right parts of the plugin :-)

**Comment by d4mation** [comment]
Ah, I didn't notice you were watching the Repo! I was actually going to ping you a bit later to ensure you saw it.

The Staging Server already has the Pre-Release on there, so that code is all the same.

If you fill out the Drip Credentials on the Settings Page and follow the brief instructions for setting up CognitoForms to ping back to the Staging Server it should work just fine. If you're testing using our accounts (Which I think I remember you got the credentials for those?) then it is already set up correctly.

Those steps you outlined are correct though :)

**Comment by jrosebr1** [comment]
Nice, just wanted to make sure we were on the same page. I have the Drip and CognitoForms credentials (the ones you guys are using) for the staging environment so I'll test those out. Once everything looks good we can also try the production credentials as well.

**Comment by jrosebr1** [comment]
@d4mation - I just went through and tested out the plugin, awesome job! Overall, everything is working great. I only found one minor "bug" of sorts.

In the two use cases that I described in the original proposal document, the plugin works 100% as expected.

Case 1: If the subscriber has the `purchased hardcopy bundle` tag and submits the CognitoForm they have the `ppao collected address` tag added. Works perfect.

Case 2: If the subscriber _does not_ have the `purchased hardcopy bundle` tag and submits the CognitoForm then they have the `ppao address suspect` tag added (and an email notification is sent out). Again, works perfect.

However, there is a 3rd case I decided to test out:

Case 3: What happens if the person enters an email address into the CognitoForm _that does not exist in Drip_? What happens then? As it turns out, even if the subscriber does not exist in Drip they are added to the Drip database and tagged. In this special case, if the subscriber is not already inside of Drip they should not be added. That makes the subscriber count increase which in turn runs up my Drip bill and fills it with potentially invalid email addresses (which hurts my email deliverability). In this special case _only_ the alert email should be sent out.

Let me know if that makes sense.

**Comment by d4mation** [comment]
Ah, that makes perfect sense. I noticed that while I was testing as well, but I figured that was intended. I actually had some code similar to this set up previously where I was checking to see if the subscriber existed, so I'll just have to add that back in.

**Comment by d4mation** [comment]
Just fixed that and uploaded it to the Staging Server. Created a New Pre-Release to go along with it. 👍

**Comment by jrosebr1** [comment]
Perfect, just tested it out and it works :-)

**Comment by d4mation** [comment]
Excellent! Would you say this is ready for a proper release, or do you still need to test it using the production credentials?

**Comment by jrosebr1** [comment]
I'll test it out with production credentials just to verify, but yes, provided everything works in production this is certainly ready for a proper release.

**Comment by d4mation** [comment]
Nice 👍 Let me know how it goes. Once we know things are still working properly with the production credentials I'll change `mail()` to `wp_mail()` and tag it for a full release.

**Comment by jrosebr1** [comment]
Hey, I just wanted to give you guys and update and let you know that I'm still testing this in production. This week has been rough and admittedly I've been very distracted. I'll have finalized feedback by the end of the weekend.

**Comment by jrosebr1** [comment]
Okay, everything is 100% up and running in production. My initial tests demonstrated that the plugin is working but I'd like to let it run for another 48-72 hours on actual live production data besides what I entered in before we call this "done" (although all signs point to that happening). Is that okay with you guys?

**Comment by d4mation** [comment]
That's fine with me. Would you want me to go ahead and finish up #6 so that once everything is said and done, all it will need is a version bump? Provided you're running this now on your Live site that is. Switching to `wp_mail()` will help prevent emails from getting sent on your Staging site.

**Comment by jrosebr1** [comment]
I'm actually using the staging server to run the plugin, just with the production CognitoForms + Drip API keys. Switching the plugin from development to production won't cause any issues. So yes, please feel free to finish up #6.

**Comment by jrosebr1** [comment]
The production credentials have been live for 24 hours and everything looks good. Feel free to finish up #6 and then mark this as the 1.0.0 release.
