### ISSUE TITLE
3 Messages Properly Tagged, But Alerted Adrian

### ISSUE THREAD

**Issue by BigActual** [realbig/PL_PYIS_ADDRESS_COLLECTION#8]
This came from Adrian last Sunday. Though it is on the docket, it did not get entered as an issue. For tracking purposes, I'm adding it in.
Adrian [6:02]
Hi Steve -- sorry to ping you on a Sunday but I'm planning on taking a few days off at the end of the week so I'm getting a jump on things.
Eric updated the plugin so that it properly sends email notifications; however, there is still a problem. I woke up this morning and found three email notifications for people who are properly tagged in Drip but the plugin alerted me for:
adrian [6:03 AM]
uploaded this image: Screen Shot 2018-04-15 at 5.16.13 AM.png
![image](https://user-images.githubusercontent.com/8271108/39094504-8110c53e-45fe-11e8-8f06-b5f83a3330e8.png)
adrian [6:03 AM]
This has been happening for the past few weeks.
The plugin needs a round of heavy debugging. I'm happy to pay for it of course, but it needs actually updating and testing. Let me know if you can schedule any time for this, and if so, when.
big_actual [1:43 PM]

**Comment by d4mation** [comment]
I used https://github-issue-mover.appspot.com/ to move the Issue from the other Repo to here so that Comments and stuff would be moved over. I'm closing this Issue in favor of that one.
